### ISSUE TITLE
Return code handling

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#109]
I was looking at the return code handling. I was trying to get the error number for a specific error
```
TSS2_ESYS_RC_BAD_VALUE:
```
but I was unable to find the error number corresponding to this.

I then looked through the code and to me it seamed  to do things perfectly fine according to the TPM specification. But the return code we get from the calls to esys APIs is not a TPM2_RC it is in fact a TSS2_RC. The ESAPI specification does not seam to mention response codes in any detailed fashion.

So my question is could there be something we are missing as the TPM_RC travels through he different layers in the software stack?

**Comment by hug-dev** [comment]
As in we cover the `TSS2_RC` values but not the `TSS2_ESYS_RC` ones? Going through the spec there are also the `TSS2_TCTI_RC` values 😨

**Comment by hug-dev** [comment]
Also I think we need to refactor the responsde code handling to make it less clunky:

```rust
let ret = Error::from_tss_rc(ret);
if ret.success() {
    ...
} else {
    ...
}
```
We should convert `ret` to a `Result<(), Error>`

**Comment by Superhepper** [comment]
I am not sure. I was just unable check if I got the error that I was interested in and I did some minor digging in the specifications but did not really come up with any answers.

From reading the specification we can say for a fact that we are not reporting the layer in software stack from where the error originated. That could be information that is worth providing.

**Comment by Superhepper** [comment]
I have started to work on this and it is 'not to bad'. It seems as we are just missing a lot of information and in some cases when the error is originating from the software stack it self and in that case we might be doing something wrong. But the errors originating from the TPM are handled correct from what I can see.

But I will refactor the response code and add support for errors originating from the software stack. But this will probably require breaking the API.
