### ISSUE TITLE
Give Superhepper the Write role

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-tss-esapi#122]
Hi @Superhepper ,

Since you helped us so much with this project and are now deeply involved in its contents, would you like to have `Write` role to help us into building the tss-esapi crate?

You can find a definition of the `Write` role [here](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) but basically that means that you will be able to approve/merge pull-requests and tinker with the CI.

We would be really happy for you to have this new role 🚀

**Comment by Superhepper** [comment]
That would be awesome. Thanks a lot.

**Comment by hug-dev** [comment]
Done, thanks for your work 💯 !!
