### ISSUE TITLE
Allow changing the public exponent for RSA keys

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#13]
In the Transient Object Context we do not allow the clients to set a custom public exponent, always defaulting to 0 (i.e. 65537). 
While the specs mention that this parameter is optional for TPM implementations, this crate should ideally support customisation for any clients that want to use it.

**Comment by hug-dev** [comment]
The [`RsaExponent`](https://docs.rs/tss-esapi/4.0.9-alpha.1/tss_esapi/abstraction/transient/struct.RsaExponent.html) could probably be helpful there.

**Comment by puiterwijk** [comment]
I'm not sure that we should support this. From a crypto point of view, I think it's easy for people to Get Crypto Wrong(R) by picking the wrong exponent.
Though from a low-level I guess we should support it.

**Comment by Superhepper** [comment]
I think we should support it but make it cumbersome. To avoid some one doing it by mistake.

**Comment by hug-dev** [comment]
Ok, closing for now as not something we will likely do anytime soon
