### ISSUE TITLE
Give puiterwijk the Write role

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-tss-esapi#130]
Hi @puiterwijk ,

Thanks a lot for your help improving the `tss-esapi` crate. Since you already made significant contributions, plan to do more and as discussed in the community meeting which minutes are going to be published and linked here soon, we would like to give the Write role.

The role will allow you to make your approvals count when reviewing PRs and to be able to merge them.

If you accept and if

- [x] @ionut-arm 
- [x] @Superhepper 

approve, let's do it 🚀 !

**Comment by hug-dev** [comment]
[Minutes](https://github.com/parallaxsecond/community/blob/master/minutes/2020-09-29.md) for reference.

**Comment by puiterwijk** [comment]
Thanks for the offer, I'll gladly accept!

**Comment by hug-dev** [comment]
Invitation sent, welcome 👌
