### ISSUE TITLE
Implement interface types

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#134]
There is a need to implement the interface types(TPMI). These types are used in a lot of the API:s and are important if we want others to be able to develop new api:s

Interface types(TPMI) are used to indicate what kind of permanent handles that can be used in certain API calls. In the NV-functions there is a 'hack'(NvAuthorization) that needs to be removed. One of these interface types that are used a lot is the Hierarchy.

One major thing with this issue is to figure out how the interface types relates to the handle types that have already been implemented.

**Comment by ionut-arm** [comment]
This sounds like a nice problem to tackle, I'll have a look at the spec for those types as well to get a feel on how they work and what they're used for in relation to the handles.

**Comment by Superhepper** [comment]
Thanks. I really appricate that.

**Comment by Superhepper** [comment]
One thing I have not been able to figure out is what DH stands for? TPMI_RH I assumed was 'resource handle'. Could TPMI_DH be 'data handle'?

**Comment by ionut-arm** [comment]
It seems possible, but looking at a few of the `TPMI_DH` types it doesn't feel right:
> TPMI_DH_PARENT
The  TPMI_DH_PARENT  interface  type  is  a  handle  that  references  an  object  that  can  be  the  parent  of another  object.  The  handles  in  this  set  may  refer  to  either  transient  or  persistent  object  or  to Primary Seeds.

Wouldn't say that's a data handle. It seems the `RH` ones reference types that have either one or a small number of possible values - something like an enum. But what `R` means is beyond me. I hate the absolute obscurity around these naming conventions - none of them are explained anywhere. Presumably Part 1 of the spec contains abbreviations, but they only put in the effort to give the abbreviations for generic stuff like `I/O` - thanks, I'm sure you can't just figure that one out with a quick search.

**Comment by Superhepper** [comment]
**TCG TPM2 r1p59 Part1 Architecture, Section 15.5**
>Fixed resource handles refer to Shielded Locations that are always associated with the same handle.
>These resources have handles with an MSO of 40 16 . Examples of these resources are Owner, Platform,
>and Endorsement hierarchy controls and the Lockout authorization value.

To me that statement seams to support my assumption that RH stands for resource handle.

**Comment by Superhepper** [comment]
RH handles seam to refer to constants. These cannot be changed. They are not even implementation dependent!

DH refers to a set or sets of handles. Each DH 'type' one or several different sets of handles are valid. And these ranges are implementation dependent!!
I think I will refer to DH as ```DynamicHandles```.
