### ISSUE TITLE
Add evict_control API to context

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#135]
We need to add support for the evict control api. I think I will do this while doing the interface types.

**Comment by ionut-arm** [comment]
The Rust KeyLime team (of which @puiterwijk is a part) is looking at implementing wrappers for [a bunch of the API calls](https://github.com/keylime/rust-keylime/issues/89), you can sync with them if you plan to upstream this - `evict_control` is one of those functions

**Comment by Superhepper** [comment]
I split this up. So that interface types were in their own PR. Now I work on the evict_control PR.
