### ISSUE TITLE
Persistent objects should not be flushed from context

### ISSUE THREAD

**Issue by Pagten** [parallaxsecond/rust-tss-esapi#152]
I noticed that when dropping the `Context` after calling `tr_from_tpm_public()` with a `PersistentTpmHandle` instance, I would get these kinds of errors and warnings:
```
[2020-11-20T21:06:15Z INFO  tss_esapi::context] Closing context.
[2020-11-20T21:06:15Z INFO  tss_esapi::context] Flushing handle 4293479
WARNING:esys:src/tss2-esys/api/Esys_FlushContext.c:234:Esys_FlushContext_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:89:Esys_FlushContext() Esys Finish ErrorCode (0x000001c4) 
[2020-11-20T21:06:15Z ERROR tss_esapi::context] Error in flushing context: value is out of range or is not correct for the context (associated with parameter number 1).
[2020-11-20T21:06:15Z ERROR tss_esapi::context] Error when dropping the context: value is out of range or is not correct for the context (associated with parameter number 1).
[2020-11-20T21:06:15Z INFO  tss_esapi::context] Context closed.
```

It seems that `tr_from_tpm_public()` adds the object handle it returns to the `open_handles` set, to automatically flush it from TPM memory upon dropping the `Context` instance. The TPM 2.0 spec says this about the `FlushContext` command:
> This command causes all context associated with a loaded object, sequence object, or session to be
removed from TPM memory.
>
> This command may not be used to remove a persistent object from the TPM.

So perhaps `tr_from_tpm_public()` should not add the object handle to the `open_handles` set if the input handle type is `Persistent`? I'm not sure if filtering out just the `Persistent` handles would cover all object types that shouldn't be flushed. Probably not, considering all the variants of the `TpmHandle` enum (shown below), but I don't know exactly which variants map to the "persistent objects" referenced in the spec.
```
pub enum TpmHandle {
    Pcr(PcrTpmHandle),
    NvIndex(NvIndexTpmHandle),
    HmacSession(HmacSessionTpmHandle),
    LoadedSession(LoadedSessionTpmHandle),
    PolicySession(PolicySessionTpmHandle),
    SavedSession(SavedSessionTpmHandle),
    Permanent(PermanentTpmHandle),
    Transient(TransientTpmHandle),
    Persistent(PersistentTpmHandle),
    AttachedComponent(AttachedComponentTpmHandle),
}
```

**Comment by ionut-arm** [comment]
Hi! Thanks for reporting this, it does indeed sound like a bug. It actually made me realize it's actually a wider problem, we should try and tackle it under this issue.

For `tr_from_tpm_public` I think a bunch of those handle types should _not_ be flushed: `Permanent`, `Persistent`, `AttachedComponent` - maybe `NvIndex` and `Pcr` but I'll defer those to @Superhepper and @puiterwijk . It might be the case that it's easier to just figure out which ones need flushing - (some of) the session handles, `Transient` for sure... For sessions, the Architecture spec says:
> All  session  contexts  in  TPM  memory  are  flushed  on  any  TPM2_Startup().  The  saved  session  contexts remain valid until a TPM Reset.

So we probably shouldn't flush those. 

The reason why I mentioned a larger issue is that I noticed `evict_control` does not do anything to the open handles. Presumably, it should check whether the operation was succesful and depending on the operation (was it transient -> persistent or the other way around) it should change `open_handles` accordingly.

Maybe we need to check all methods again, make sure they all keep `open_handles` consistent. Maybe we also need some methods on `Context` to let the user decide if some handles shouldn't be flushed - it would also help mitigate any problem like this in the future.

**Comment by Superhepper** [comment]
I think that the specification says it pretty clear:
> When an authorization session is no longer needed, TPM2_FlushContext() 
>may be used to delete all context associated with the session from TPM memory (see 30.6). 
>The session handle for this command may use an upper octet of either 0x02 or 0x03.

>All Transient Objects are flushed from TPM memory on any TPM2_Startup(). 
>A loaded Transient Object context may be flushed from TPM memory using 
>TPM2_FlushContext() and indicating the handle of 
>the loaded context to be flushed.

So ```flush_context``` can only be used if the handle is a HmacSession, LoadedSession or Transient.
But one thing that should be done for all handles when the context is dropped is to close them.
That is not so complicated to check for in ```tr_from_tpm_public()```

To take care of the handles from ```evict_control``` what we would have to do is:
-If you make something persistent then you will have to look that handle up and say 'close but not flush'. 
-If you make something non persistent then you would have to say 'close and flush'.

**Comment by Superhepper** [comment]
I got it all wrong. Either you flush a handle or you close a handle. You cannot do both. FlushContext removes all the data from the TPM and cleans up all the Esys resources while close only cleans up the Esys resources and should therefor be used with handles that we are not allowed to flush.

**Comment by Superhepper** [comment]
I may also have run into a bug in tpm2-tss when trying to get this to work.
https://github.com/tpm2-software/tpm2-tss/issues/1930
