### ISSUE TITLE
Key management approach in abstraction::transient won't work in windows

### ISSUE THREAD

**Issue by gaetanww** [parallaxsecond/rust-tss-esapi#169]
The commands `TPM2_ContextSave` and `TPM2_ContextLoad` are [blocked by the OS on windows](https://github.com/microsoft/TSS.MSR/issues/39).
Maybe consider a different approach? Like returning `out_public` and `out_private` instead of a `TPMS_CONTEXT` when creating the key and reloading the key when using with `context.load`?

**Comment by Superhepper** [comment]
Right now and in the versions that are close to be released Windows is not a platform that we currently support. But we would happily accept any PR:s that would add windows support. In order for that to happen the CI needs to be run on that platform with the latest packaged version of the compiler available for that platform.

**Comment by gaetanww** [comment]
Understood! However, if you did want to support Windows in the future, you will have to rearchitect your abstraction module or have different behaviour on Windows and Linux. However you could have sensibly the same abstraction API by using TPM2_Load. Would it be a better way forward?

**Comment by ionut-arm** [comment]
Hi! Thanks for reporting this, it's quite an interesting path they took, restricting the usage of `ContextSave` and `ContextLoad`. As @Superhepper was saying, we were not actively looking at Windows integration and the `abstract` module in particular was created for the Parsec service. Depending on whether we'll want to add Windows support for the service, we might have to re-architect that abstraction.

I'm curious why they went that far, to actually prohibit apps from using the methods. The spec does say that
> The TPM Resource Manager (TRM) is responsible  for  swapping  the  contexts  so  that  the  necessary  resources  are  present  in  the  TPM  when needed

And my guess is that they've implemented a resource manager and consider the issue settled. 

I'll leave the issue open so we can have a wider debate about it when everyone's back from holidays

**Comment by gaetanww** [comment]
Fair enough! :) I ran into that issue on windows while using the resource manager (TBS) but I didn’t try to connect directly to the device and see if the commands are still blocked. 
It made me wonder though if using the ContextSave and ContextLoad commands independently of the TRM could create an inconsistent state if the TPM used by multiple applications at the same time.

**Comment by ionut-arm** [comment]
> It made me wonder though if using the ContextSave and ContextLoad commands independently of the TRM could create an inconsistent state if the TPM used by multiple applications at the same time.

I'm not sure if that's even possible - I remember trying to use `/dev/tpm0` directly on a system that had an active resource manager and it was impossible, it was complaining that the component is busy/in use or something like that. But the service did work correctly when the RM was used. Don't know if that's also the case when the kernel RM is involved as well, but I do see how it could backfire.
