### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by baloo** [parallaxsecond/rust-tss-esapi#192]
This is not an issue. I just wanted to reach out and express gratitude for the work!

I recently started to experiment with TPM, and this crate and is so much easier to use than anything else I could try (C, Python, ...).
I've been able to get a prototype done in a couple hours (and I'm confident I didn't mess up the memory model (!)), where I couldn't get anything meaningful before. Thank you for the care you gave to the API, it's great.

**Comment by ionut-arm** [comment]
I'm glad you're finding it useful! I think the biggest shout-out goes to @Superhepper who's been toiliing over a nice, clean, usable abstraction for a while :) We promise we'll get to a stable release at some point

**Comment by Superhepper** [comment]
Thank you @baloo I am glad you like it. It is always good to get fresh pair of eyes on the code. To point out things that can be improved. Please share any suggestions you have for improvement in the discussion section of the repo.
