### ISSUE TITLE
Investigate which FFI types are still in the `tss-esapi` interface

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#222]
Now that we have a separation between the `tss-esapi` and `tss-esapi-sys` crates, we should focus on removing all FFI data types from the interface of `tss-esapi`. While we cannot change the interface for any 5.x.y release, we can still write up abstractions for all these types and replace them when we're ready for a major version bump. 

This issue is just an investigation for which types are still being used straight from `-sys`. New interfaces SHOULD NOT use FFI types and should instead create new abstractions (or use the Rust native types, if they exist).

Depending on how difficult to abstract they are, we could create separate issues for the work, e.g. a separate issue for `TPM2B_PUBLIC`.

**Comment by Superhepper** [comment]
This is now part of the much larger issue https://github.com/parallaxsecond/rust-tss-esapi/issues/290 can there for be closed.
