### ISSUE TITLE
The symmetric parameter should be optional in start_auth_session context method.

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#228]
From what I can tell the specification does not require you to provide a symmetric definition. If one does not want the parameters to be encrypted it is also possible to send ```TPM2_ALG_NULL``` this is currently not supported. So the symmetric parameter should be changed to an ```Option<SymmetricDefinition>``` and if None then ```TPM2_ALG_NULL``` should be used.

*TCG TPM2 r1p59 Part3 Commands, Section 11.1.2 Command and Response, Table 15*
>TPMT_SYM_DEF+ | symmetric | the algorithm and key size for parameter encryption may select TPM_ALG_NULL |

**Comment by ionut-arm** [comment]
That makes sense. It's a breaking change, though - do you need it published soon?

**Comment by Superhepper** [comment]
I was to fast i think because you can actually do ```SymmetricDefinition::Null```. So I do not this is a valid issue.

**Comment by Superhepper** [comment]
We could add it as a convenience so it is clear that it is optional but it is not a bug.

**Comment by Superhepper** [comment]
This should be closed it is not valid.
