### ISSUE TITLE
Create and deploy enums for algorithm types

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#23]
Using enums as parameters for algorithm types would help enforcing correct usage of the values involved.

E.g. for the `Tpm2bPublicBuilder`, `with_type` and `with_name_alg` would benefit from stricter compilation checks.

**Comment by Superhepper** [comment]
The enum for algorithmic types have already been created in #60. This issue is more about putting it to good use.

**Comment by ionut-arm** [comment]
Indeed, but I think just having the enums is a big step forward!

**Comment by hug-dev** [comment]
Is that still up to date?

**Comment by Superhepper** [comment]
Yes, there are still a lot of places where the TPM2_ALG_ID is used instead of proper enum.

**Comment by ionut-arm** [comment]
It seems that at least `TPM2_ALG_ID` isn't as common now in its raw form, so I'll close this. I will open a new issue to investigate which remaining structures we use straight up from the `-sys` crate (e.g. the infamous `TPM2B_PUBLIC`), and new issues for abstracting away each one those (to create a native version and then replace all occurences when we move to 6.x.y).
