### ISSUE TITLE
Create enum wrappers around resource handle types

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#24]
Resource handle types that have various variants (e.g. hierarchies) would benefit from better static enforcing through Rust enum wrappers.

**Comment by Superhepper** [comment]
Work for the TPM handles where made in #108 but that left the Esys handles to just one type which isn't really correct.

Something similar needs to be done for the esys handles.

**Comment by Superhepper** [comment]
This have in general been solved. There might still be things to do but that can be handled as separate issues.
