### ISSUE TITLE
Manually construct PcrData?

### ISSUE THREAD

**Issue by lkatalin** [parallaxsecond/rust-tss-esapi#277]
I'm working on a project (the [Rust Keylime agent](https://github.com/keylime/rust-keylime)) that makes use of the `rust-tss-esapi` extensively.

One of our critical and urgent bugs is that we are not able to read > 8 PCRs at a time. I currently have a draft of a way to fix this in our own codebase by doing several reads and stitching together the resulting `(hashalg, bank)`s into a vec. Yet I'm not able to turn this vec into a `PcrData` as `PcrData.data` is a private field and there is no method to construct a `PcrData` from this type of vec.

The simplest fix for my specific problem would be to make `PcrData.data` public - would this be acceptable?

I also realize this isn't the "right" way and the actual fix should probably be here in the `rust-tss-esapi`. I haven't attempted a PR for this as it seems like a large task and I'm not very familiar with this code. But I could have a try at it if that would be the way forward.

Please advise!

**Comment by ionut-arm** [comment]
Would this mean a method on `Context` that does multiple calls to the TPM and then stitches the results together? Tbh that sounds pretty good - it veers slightly into the territory of abstractions, but this seems like a very reasonable exception.

**Comment by Superhepper** [comment]
No, I was more thinking of an function under abstractions looking something like this:
```rust
pub fn read_all(context: &mut Context, pcr_selection_list: PcrSelectionList) -> Result<PcrData>
```

**Comment by lkatalin** [comment]
Made some progress. I get an `ActivateCredential` error when I switch to using your branch `Superhepper:pcr_read_return_types_change` with commit `33f6e52` as a dependency, though I remember getting this error a month ago when pinning to the `rust-tss-esapi` Github repo instead of `6.1.x` so I think it is not related to your specific change:

```
WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:321:Esys_ActivateCredential_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:105:Esys_ActivateCredential() Esys Finish ErrorCode (0x00000101) 
Error: Tpm { err: Tss2Error(FormatZero(FormatZeroResponseCode { .0: 257, error_number: 1, format_selector: false, version: true, tcg_vendor_indicator: false, severity: false })), kind: Some(Failure), message: "commands not being accepted because of a TPM failure. NOTE: This may be returned by TPM2_GetTestResult() as the testResultparameter" }
```

I didn't make any headway on this when I first encountered it - any ideas? Or should I open a separate issue?

**Comment by Superhepper** [comment]
hrmm, I have never seen that error before that I know of. I doubt it has anything to do with the changes in the PR.

**Comment by Superhepper** [comment]
I mean my change is based on master so there is a quite a lot of things that have happened since 6.1.0. Have you tried to compile with 7.0.0-alpha from crates.io? Or just the master to see if the error goes away? So it perhaps would be possible to narrow it down a little.

And maybe @ionut-arm would have some clues of what might be going on here?

**Comment by lkatalin** [comment]
Thanks, @ionut-arm @Superhepper . If I'm able to, I'll try to narrow it down later today and I can open a new issue with more details. In the meantime, @ueno may also be able to give the draft PR #281 a try as well.

**Comment by lkatalin** [comment]
One thing I am noticing as I investigate this and document the issue is that due to the change from `TPM2B_PUBLIC` to a `Public` type [here](https://github.com/parallaxsecond/rust-tss-esapi/pull/241) I end up having to update our Keylime code to have a line `let ak_tpm2b_pub = ak.out_public.clone();` - could cloning a `TPM2B_PUBLIC` cause an `ActivateCredential` error? I get the error whenever I switch away from `6.1.1` as a dependency and I am having to make this code change at exactly those time as well.

If that doesn't make sense I will go ahead and open the new issue, I'm just trying to eliminate the possibility that I'm doing something silly.

**Comment by ionut-arm** [comment]
Hmmm, I hadn't looked too closely at the error code you were getting, but digging a bit deeper, it seems the return code is `TPM_RC_FAILURE` about which [the Architecture spec](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf) says, in section 12.4:

> If  the  TPM  fails  an  internal  test,  it  enters  Failure  mode.  While  in  Failure  mode,  the  TPM  returns TPM_RC_FAILURE in response to any command except TPM2_GetTestResult() or TPM2_GetCapability() (see Figure 7).

It sounds like something else happened _somewhere_, which leads to that RC being returned indiscriminately, and maybe Keylime just errors out at the first one it encounters? Do you run a TPM self-test when starting?

**Comment by Superhepper** [comment]
The public structure only contains data. There is no state in there. So I do not believe that is the problem.

**Comment by lkatalin** [comment]
I'll go ahead and open a new issue to track this and provide more details there.
