### ISSUE TITLE
Document PublicKey

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#279]
The `PublicKey` type (used in `TransientKeyContext`) isn't documented as to what the format of the data in each variant is. This must be rectified.

**Comment by ionut-arm** [comment]
More documentation (more specifically code examples for how to actually use the `TransientKeyContext`) should be added, to make the context more user-friendly.

**Comment by bootstrap-prime** [comment]
I'm attempting to build an ssh-agent on top of this library and the lack of documentation is confusing. Judging from parsec, is it just the raw components? Even if you don't document them, could you describe them? Same for signature. also judging from parsec, I think they're also raw?

**Comment by ionut-arm** [comment]
Hey! Thanks for the feedback, I'll try to add some documentation today, though it will focus on `TransientKeyContext` - for the lower level stuff (around `Context`) it's better to just use the spec as the documentation, and we can help with navigating that as well. I'll also summarise it in a comment here, since I'm not sure when we'll be pushing out the next release.

**Comment by ionut-arm** [comment]
I've opened #347 - let me know if you'd also like a summary here as well, or if the PR is enough to get you going :)

**Comment by bootstrap-prime** [comment]
That helps, thank you very much! I might have more questions in the future but this is probably enough to get me going.

**Comment by ionut-arm** [comment]
Done in #347
