### ISSUE TITLE
Split in tss-esapi and tss-esapi-sys

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#30]
~Builds are broken for generating the docs for publishing on docs.rs due to the TSS libraries not being installed on the Docker image where the build takes place. Unfortunately there seems to be no quick way to fix this (e.g. by installing a system package).~

The proposed solution is to set up dynamic loading through [`libloading` ](https://crates.io/crates/libloading) . This implies creating a new type of FFI binding which can only be hand-crafted, as `bindgen` does not currently support it (see https://github.com/rust-lang/rust-bindgen/issues/1541 ). 

Alternatively, the work for adding the support in bindgen for this case could be done.
Or, the TSS include files can be pulled as a submodule.

EDIT: Initial problem was fixed by adding static bindings ESAPI that are used only for creating documentation. Thus, an issue still exists around removing said bindings and one of the suggestions above should be used.

**Comment by hug-dev** [comment]
That would be solved by implementing the `-sys` approach: split the repo into a `tss-esapi` and `tss-esapi-sys` crates, with the `tss-esapi-sys` compiling from the source if the libraries are not installed on the system 😃

**Comment by ionut-arm** [comment]
@joechrisellis 's PR for bindgen ( https://github.com/rust-lang/rust-bindgen/pull/1846 ) will come in handy, as we can now rely on bindgen for dynamic loading.

**Comment by ionut-arm** [comment]
#75 is a duplicate of this, closing that one - whenever this gets picked up, please review the comments there too!

**Comment by ionut-arm** [comment]
#85 is also quite relevant - if anything, they should be done together
