### ISSUE TITLE
Hierarchy/Unseal/Load auth value

### ISSUE THREAD

**Issue by fer9898** [parallaxsecond/rust-tss-esapi#309]
Hello,

I'm trying to translate something like that:
```
tpm2_changeauth -c owner test
tpm2_createprimary -C owner -c primary.ctx -p test
tpm2_create -C primary.ctx -u obj.pub -r obj.priv -P test
tpm2_load -C primary.ctx -u obj.pub -r obj.priv -c key.ctx -P test
```
in Rust.

I got two problems:

1) I want to specifiy a hierarchy auth value, but I don't know how to do that, in the documentation, there is no `auth_value` argument in the Context construction ([docs](https://docs.rs/tss-esapi/7.0.0-alpha.1/tss_esapi/struct.Context.html#method.new))

2) I want to specify an auth value for my key (not the primary one), I can do that with the `auth_value` argument of the `create()` function ([docs](https://docs.rs/tss-esapi/7.0.0-alpha.1/tss_esapi/struct.Context.html#method.create)), but when I want to load that key, I can't provide an `auth_value` argument ([docs](https://docs.rs/tss-esapi/7.0.0-alpha.1/tss_esapi/struct.Context.html#method.load)), so my program isn't able to load the key. (If I don't use auth value, everything is working fine)

So is this possible in the current version of the crate ?

**Comment by ionut-arm** [comment]
Hey!

Thanks for getting in touch, the answer to both of your questions is to use the [`tr_set_auth`](https://docs.rs/tss-esapi/7.0.0-alpha.1/tss_esapi/struct.Context.html#method.tr_set_auth) method on `Context`. This allows you to set authentication values for handles, which will then be used by the software stack underneath our crate to authenticate commands and so on. For an example, you can see an example of loading an auth value for hierarchies [here](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/src/abstraction/transient/mod.rs#L649), and one for loading the auth value for keys [here](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/src/abstraction/transient/mod.rs#L516). For hierarchies you just convert a variant of [`Hierarchy`](https://docs.rs/tss-esapi/7.0.0-alpha.1/tss_esapi/interface_types/resource_handles/enum.Hierarchy.html) into that `object_handle` parameter, while for keys you convert the key handle you got after loading them.

Actually, if your main goal is to create, load and use keys in the way that you've mentioned in that snippet, you might be better off just using [`TransientKeyContext`](https://docs.rs/tss-esapi/7.0.0-alpha.1/tss_esapi/abstraction/transient/struct.TransientKeyContext.html) for the whole process, as it takes care of all these small details.

Apologies for not having enough documentation to make all of this clear. We'll get to it one day, when we're done with polishing the API, probably :] You can find some examples of using the transient context in [the tests for it](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/tests/integration_tests/abstraction_tests/transient_key_context_tests.rs).

**Comment by fer9898** [comment]
Hey @ionut-arm 

Thank you really much for you answer, I succesfully implemented this thanks to your help.

No problem for the documentation, as you said this will come with time, and this is clearly not the worst case I have seen don't worry, the current documentation actually helped me for quite a few things.
