### ISSUE TITLE
rust-tss-esapi-7.0.0-beta.1 tag not pushed to git

### ISSUE THREAD

**Issue by nullr0ute** [parallaxsecond/rust-tss-esapi#321]
There's a rust-tss-esapi-7.0.0-beta.1 release on crates.io but not the corresponding tag in the git repo

**Comment by nullr0ute** [comment]
Similarly the tss-esapi-sys 0.3.0 release tag doesn't look to be pushed either

**Comment by ionut-arm** [comment]
Done now

**Comment by nullr0ute** [comment]
:+1: thanks
