### ISSUE TITLE
7.0.0-beta.1: AK template can no longer be customised

### ISSUE THREAD

**Issue by rshearman** [parallaxsecond/rust-tss-esapi#322]
Post commit a4dbdc797c1de994b5ef901e9b25c299a3a6e605, the create_ak API no longer supports customising the key beyond its object attributes. This is due to the following change:

```
-    };
-
-    let key_builder = if let Some(ref k) = key_customization {
-        k.template(key_builder)
-    } else {
-        key_builder
-    };
-
-    key_builder.build()
+    }
```

I don't know if this was intentional or not, but if it is then it's probably worth documenting that the key customisation template method won't be called.

Cc: @Superhepper

**Comment by ionut-arm** [comment]
Thanks for the report, let me try to quickly update that.
