### ISSUE TITLE
Investigate adding Valgrind to CI

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#339]
Because the TSS stack underneath us hands over to us ownership of data it has allocated, there is always a risk that we don't clean up properly after this handover, and that some memeory is leaked.

We should investigate how we could enable Valgrind tests on the CI to catch such problems, and whether some problems already exist.

**Comment by Superhepper** [comment]
I think this would be an excellent choice:
https://github.com/jfrimmel/cargo-valgrind

But we might need to wait to use it in CI before we are able configure it more(https://github.com/jfrimmel/cargo-valgrind/issues/37). And we might need to be able to add suppressions in some manner.

**Comment by ionut-arm** [comment]
Done in #344
