### ISSUE TITLE
Handle TPMS_CONTEXT more robustly

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#36]
When produced by bindgen on certain platforms, `TPMS_CONTEXT` adds an empty padding field to the end of the structure. Currently we do not make sure that this is factored into any usage of the structure, causing compilation failures on said platforms. 

An example so far is in the `TryFrom<TpmsContext>` implementation. The fix would be to simply add a `..Default::default()` to [TOTC](https://doc.rust-lang.org/nightly/nomicon/constructors.html) of `TPMS_CONTEXT`.

Maybe this should be added to all bindgen-generated structs (or manually check the ones that could require padding on platforms with different word sizes)?

**Comment by hug-dev** [comment]
If the issue appear when compiling for a platform with a 32 bits word size and that `TPMS_CONTEXT` was the only structure which contained the padding then maybe we can assume that it is the only structure that we need to fix? As in, the issue will not happen in the future for any other structure when compiling for a 64 or 32 bits target?

**Comment by hug-dev** [comment]
Meaning that we do not need to add the `..Default::default()` to all of our structures

**Comment by ionut-arm** [comment]
Do we care about 16 bit platforms? 🤡

**Comment by hug-dev** [comment]
Let's write Parsec on a punched card 🤡

**Comment by ionut-arm** [comment]
Issue was fixed in #41
