### ISSUE TITLE
Importing pem key to the TPM

### ISSUE THREAD

**Issue by DNJha** [parallaxsecond/rust-tss-esapi#361]
I want to load a key pair generated by OpenSSL to the TPM. I was trying to use `context.import()` function but it seems to be available only for the importing the duplicate keys. Any help is much appreciated.

**Comment by ionut-arm** [comment]
Hey, perfect timing! @gowthamsk-arm - I think your input would be useful here :)

I know @wiktor-k has also done some work on this, but I think he's out for a while!

**Comment by gowthamsk-arm** [comment]
Hi @DNJha thanks for raising this issue. Currently, there is no support in TransientKeyContext to import externally generated public/private key pair in the crate. We will be developing the functionality for it in the coming days. If you want to import only the external public key to TPM, you can use the load_external_public_key function of TransientKeyContext.

**Comment by DNJha** [comment]
Thanks @ionut-arm and @gowthamsk-arm for the quick response.

I want to sign data using the loaded key, so I don't think load_external_key is the proper function. I'll wait for the import_pem function to be available.

**Comment by wiktor-k** [comment]
What's the use case? Why not just sign the data using openssl?

I don't have access to the computer right now but if I were you I'd extract private key bits using openssl crate and then use these bits in [load external](https://docs.rs/tss-esapi/latest/tss_esapi/struct.Context.html#method.load_external). See [this code example using older API](https://gitlab.com/wiktor/tpm-openpgp/-/blob/main/src/lib.rs#L433). Key loaded like that works just fine for signing but note that you won't be able to persist it (private keys can be loaded only in Null hierarchy).

If you want to load private key and make it persistent it's more complex: you'd have to go through the duplication flow and if you do that why not generate the key in the TPM in the first place? 

Maybe you can describe what you want to do so we can avoid falling into the [XY Problem](https://en.m.wikipedia.org/wiki/XY_problem) trap.

**Comment by DNJha** [comment]
Thanks for your suggestion @wiktor-k.

In my case, I have a given key pair in the pem format (generated by OpenSSL). I want to use this to sign a series of data. Now, I could do this with the key directly, but in my scenario, I need the sign to be generated by the TPM. Also, the data is in series, so I want the loaded key to be persistent. 

I thought import_pem is the best solution but I can try some other ways to do that. I'm open to any suggestions.

**Comment by DNJha** [comment]
Thanks @wiktor-k. This really helped me. I'm doing the later step to make it persistent.

**Comment by DNJha** [comment]
This question may seem silly but I'm struggling with this. 

@wiktor-k I followed your instructions and generated a duplicate key and imported it to the TPM (using `import`) and get the private key as a return. However, I can't load the private key (generated by the duplicate) + public key to the TPM using the `load` operation. To perform the sign, I need to load the key pair to get a TPM handle. I'm not sure what am I missing.
