### ISSUE TITLE
Getting a `TpmHandle` from an `ObjectHandle`.

### ISSUE THREAD

**Issue by mdcarr941** [parallaxsecond/rust-tss-esapi#362]
The ESAPI allows an application to convert an `ESYS_TR` handle to a `TPM2_HANDLE` via the function `Esys_TR_GetTpmHandle`. This is useful, for instance, if you want to evict a persistent object, as you have to supply both an object handle and a persistent handle to `Esys_EvictControl`.

I believe the equivalent operation using the types in `tss-esapi` would be converting an `ObjectHandle` to a `TpmHandle`, but I haven't found a way to do this. Failing that, I thought  I could just call the `Esys_TR_GetTpmHandle` function directly, but I found that `tss-esapi-sys` doesn't expose it. In fact, there are no references to `Esys_TR_GetTpmHandle` in this repository.

That said, these are my questions:
- Is there a way to perform this conversion using `tss-esapi` directly?
- If the answer to the first question is no, would you be willing to review a pull request which adds the following method to `Context`?
```
pub fn tr_get_tpm_handle(&mut self, object_handle: ObjectHandle) -> Result<TpmHandle>;
```

**Comment by Superhepper** [comment]
Let me begin by answering your second question first.

That API has not yet been implemented. And would we be willing to review a pull request that adds that functionality? Absolutely!


Is there a way to retrieve the tpm_handle for a specific handle using the current API? 
Maybe, but that solution would be so absurd I do not think I will even go into it in detail.  But It would involve looping over all
possible TPM handles and then compare the name of the object ```tr_get_name``` to the name of the object referred to
by the ObjectHandle that you have. 

Is there a way to call the underlaying ESAPI directly?
Yes. All the TSS apis are exposed under the ```tss2_esys```module. 

Problem 1: The Context struct does not
not allow it self to be converted into the ESYS_CONTEXT type. Which means you would have copy the steps in the ```Context::new()``` to get your self a context object. Then you could use that object to call the ```tss_esapi::tss_esys2::Esys_tr_get_tpm_handle```.

Problem 2:
Creating a second ESYS_CONTEXT without using a TABRMD tcti will probably result in your program blocking forever on the creation of the second context or an error. I am also not entirely sure that you will be allowed to use a transient ObjectHandle from one context in a call using another context.

**Comment by ionut-arm** [comment]
Just as a quick explainer - I think we're missing `Esys_TR_GetTpmHandle` because we use version 2.3.3 of the tpm2-tss headers, which don't contain it. Perhaps for v8 of the crate we should move to 2.4.x of tpm2-tss! That would solve part of the problem, and would allow for an easier solution for this, I assume.

**Comment by mdcarr941** [comment]
@Superhepper, I believe I found a convoluted work-around to use `Esys_TR_GetTpmHandle`. I can convert the `ObjectHandle` to an `ESYS_TR`, serialize it to a `TPMS_CONTEXT` using `Esys_ContextSave`, create a new context by calling `Esys_Initialize`, deserialize the `TPMS_CONTEXT` using `Esys_ContextLoad`, and finally call `Esys_TR_GetTpmHandle`. You have to perform the serialization because `ESYS_TR` handles aren't portable between contexts (clause 3.3 of v1.00 of the ESYS spec), and of course this would require a TABRMD between me and the TPM.

Instead of that complicated stuff, for now I've decided to save the `TPM2_HANDLE` directly, as it's just a `u32`. Then I can recreate the `ObjectHandle` on the next program invocation with `Context.tr_from_tpm_public`. I would have preferred to put `TpmHandle` in my serializable struct, but because it doesn't implement `Serialize` and `Deserialize` I've settled for using the underlying type. This does mean more traffic between my program and the TPM, but it's only one additional command for each `ObjectHandle` at startup. This is fine for my application, but it could be a problem for an application that's running in a virtualized environment with lots of contention between containers accessing the TPM.

@ionut-arm, Upping the minimum supported version of tpm2-tss is a big decision, but if that's done it should be easy to implement the context method I mentioned in my opening post. I'll go ahead and close this issue as I have a work-around and the improved solution will have to wait for a later version of the crate.

**Comment by Superhepper** [comment]
It would be possible to create an implementation that is dependent on version using ```#[cfg(has_esys_tr_get_tpm_handle)]...? For users who generate their own tss-esapi-sys.

**Comment by Superhepper** [comment]
@mdcarr941 @ionut-arm We could probably do something that looks like this.

This could probably be backported to version 6 and 7 of the crate with a few new dependencies.

Add the following to *build.rs*
```rust
let has_esys_tr_get_tpm_handle_req = VersionReq::parse(">=2.4.0").unwrap();
if has_esys_tr_get_tpm_handle_req.matches(&tss_version) {
    println!("cargo:rust-cfg=has_esys_tr_get_tpm_handle")
}
```

*tss-esapi/src/context/general_esys_tr.rs*:
```rust
cfg::cfg_if! {
    if #[cfg(has_esys_tr_get_tpm_handle)] {
     <CODE AND DOCUMENTATION HERE>
    }
}
```

**Comment by mdcarr941** [comment]
@Superhepper, Thanks for pointing me in the right direction. I've created a [PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/363) with the additions that we discussed. I found that I needed to make the code in the build script conditional on the `generate-bindings` feature being enabled, otherwise I got a build failure when this feature was off.
