### ISSUE TITLE
Create auth value wrapper

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#37]
The transient object context gets an Owner hierarchy auth value as a slice of bytes which may be convenient in some circumstances, however it puts the burden on the clients to bring the value in this shape.

A better solution is to create a generic wrapper for Auth values that can be created from strings or byte slices. For strings, these should allow parsing "TSS2 CLI tools"-style strings, i.e. checking for prefixes like `str:` for string auth values, or `hex:` for hex encoded binary values. E.g. https://www.mankier.com/1/tpm2_startauthsession#Authorization_Formatting

In the future this structure could be expanded to stand for policy and/or PCR-based authentication values.

**Comment by hug-dev** [comment]
Is that now implemented?
