### ISSUE TITLE
Replacing `MBox`

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#371]
[`Mbox`](https://github.com/kennytm/mbox) seems to have gone out of maintenance - specifically, there are lots of PRs open, and (serious-looking) issues that have no reply on them. We should decide whether we want to continue with `Mbox`, switch to a different crate doing the same thing, or if we want to implement our own functionality for the stuff that we need.

We're currently sticking with `Mbox` by default, but that might not be a great idea in the long run - I also expect it to be reported as unmaintained in the Cargo audit database at some point, it won't look good for users of `tss-esapi` if we keep using it.

An alternative crate that seems to be maintained and does similar things is [`malloced`](https://crates.io/crates/malloced). However, it seems to be less popular, at least for now.

The last option is for us to copy the functionality that we care about into our crate and use that. That might be the "safest" option, but it could also come with some overhead, especially if it turns out to be quite a big chunk of code. But I'd lean towards this - I think we've been somewhat limited in our use of `MBox`.

**Comment by ionut-arm** [comment]
It would also allow us to integrate "natively" stuff like [this](https://github.com/parallaxsecond/rust-tss-esapi/pull/365#discussion_r958282102) instead of writing helpers around `MBox` for it.

**Comment by Superhepper** [comment]
I have looked at some of the alternatives and to me they did fit as well as MBox does. So I wonder if it would be possible to fork off MBox and continue development on the fork. Or maybe create or own crate for handling this.
