### ISSUE TITLE
Certificate Signing Request (CSR) for TPM primary key handle

### ISSUE THREAD

**Issue by DNJha** [parallaxsecond/rust-tss-esapi#374]
I want to create a CSR for TPM's primary key handle, which will be sent to the certificate authority for signature. I can get the public key from the TPM handle but the CSR generation requires the private key. 

I found that OpenSSL provides an `engine` flag where we can specify a hardware device instead of the private key. Can I use something like that with Rust TSS_ESAPI or is there any other way to generate the CSR?

Any help is appreciated.

**Comment by ionut-arm** [comment]
Hey!

We currently don't have any functionality in the crates that would do this for you, but it could be something worth adding in the `abstraction::public` module. There are "easy" ways to generate a CSR available through other libraries in the Rust ecosystem. For example, we have an implementation for a CLI tool that does exactly that [here](https://github.com/parallaxsecond/parsec-tool/blob/main/src/subcommands/create_csr.rs), using [rcgen](https://docs.rs/rcgen/0.9.3/rcgen/). You could easily adapt that by converting a `Public` structure from `tss-esapi` to [`DecodedKey`](https://docs.rs/tss-esapi/7.1.0/tss_esapi/abstraction/public/enum.DecodedKey.html). You can then encode the nested `RsaPublicKey` or `EcPoint` to DER via [`picky-asn1-der`](https://docs.rs/picky-asn1-der/0.3.1/picky_asn1_der/fn.to_bytes.html) and use it as in our `rcgen` example from above.

Feel free to ask more questions if you get stuck.

**Comment by DNJha** [comment]
Thanks for your suggestions. I'll follow as you suggested and let you know.

**Comment by DNJha** [comment]
Hi @ionut-arm, 

I'm trying to do what you suggested but having two issues:
a) When I'm trying to convert the public key (in DecodedKey format) to DER using `picky_asn1_der::to_bytes(&decoded_key, buffer).unwrap()`, I'm getting an error  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedType'
b) I'm unable to understand the relation between `parsec_client::BasicClient` and the crypto provider (TPM handle in our case) 

Thank you, any suggestion is appreciated

**Comment by ionut-arm** [comment]
> a) When I'm trying to convert the public key (in DecodedKey format) to DER using picky_asn1_der::to_bytes(&decoded_key, buffer).unwrap(), I'm getting an error thread 'main' panicked at 'called Result::unwrap() on an Err value: UnsupportedType'

Hmm, indeed, this seems to be a bug, we'll probably have to implement `Serialize` and `Deserialize` manually for `DecodedKey`, as picky isn't picking it up. In the meantime you can `match` on that `DecodedKey` and serialize what's inside - that should work for both EC and RSA keys.

> b) I'm unable to understand the relation between parsec_client::BasicClient and the crypto provider (TPM handle in our case)

The `BasicClient` implementation is just for reference, you'd need to replace the operations that are implemented by it with something using the `tss-esapi` crate. For example, instead of using the `parsec_client` to sign the message [here](https://github.com/parallaxsecond/parsec-tool/blob/main/src/subcommands/create_csr.rs#L257), you can instead use the `tss-esapi` [`Context::sign`](https://docs.rs/tss-esapi/latest/tss_esapi/struct.Context.html#method.sign)

**Comment by DNJha** [comment]
Hi @ionut-arm 

I managed to do everything as you suggested. There is just one error I'm facing now related to the `sign` function. 
`Error in converting to vector: WrapperError(WrongParamSize)`.

The size of data generated by the CSR generation is 410 and the max size specified for the [digest](https://github.com/parallaxsecond/rust-tss-esapi/blob/afc921185d2b2ca7969334eaa928c4a1019d6e3e/tss-esapi/src/structures/buffers.rs#L123) is 64.

I'm trying to extend the `impl TryFrom<Digest> for [u8; 64]` to `impl TryFrom<Digest> for [u8; 410]` but not able to. 

Any help is appreciated. Thank you.

**Comment by ionut-arm** [comment]
Hey! You'd most likely need to hash the data before signing it. If you use a key that expects SHA256 as the signing algorithm, for example, I'd suggest using [this](https://docs.rs/sha2/0.10.6/sha2/) crate to calculate the hash.

**Comment by DNJha** [comment]
Thank you so much. I can successfully generate the CSR now.
