### ISSUE TITLE
Converting a private key to Sensitive type for load_external()

### ISSUE THREAD

**Issue by DNJha** [parallaxsecond/rust-tss-esapi#381]
I'm trying to use [load_external](https://github.com/parallaxsecond/rust-tss-esapi/blob/4620f3f140652675351d6793fd085e62b2b95d76/tss-esapi/src/context/tpm_commands/object_commands.rs#L133) function for importing an RSA 2048 key-pair to the TPM. As given in the example, I used [get_ext_rsa_priv](https://github.com/parallaxsecond/rust-tss-esapi/blob/ac7efa40cbcbb50eadd9b30e5360273f91a7900d/tss-esapi/tests/integration_tests/context_tests/tpm_commands/object_commands_tests.rs#L181) and [get_ext_rsa_pub](https://github.com/parallaxsecond/rust-tss-esapi/blob/ac7efa40cbcbb50eadd9b30e5360273f91a7900d/tss-esapi/tests/integration_tests/context_tests/tpm_commands/object_commands_tests.rs#L189). However, get_ext_rsa_priv fails to execute. After adding basic error handling using expect as given below, the error makes some sense.

> pub fn get_ext_rsa_priv(priv_key: Vec<u8>) -> Sensitive {
>     Sensitive::Rsa {
>         sensitive: priv_key
>             .to_vec()
>             .try_into()
>             .expect("Error in converting the private key to vector"),
>         auth_value: Default::default(),
>         seed_value: Default::default(),
>     }
> }

`thread 'main' panicked at 'Error in converting the private key to vector: WrapperError(WrongParamSize)'`

Any suggestion to resolve this issue

**Comment by wiktor-k** [comment]
:thinking: I saw similar errors when trying to import a 1k RSA key to my hardware TPM but with 2k it should be fine. Just out of curiosity could you try with the emulator and see if it works?

**Comment by DNJha** [comment]
Hi @wiktor-k, thanks for your reply.

Unfortunately, I'm getting the same error for the 2048 bits RSA key (same error for the 512 bits RSA key too).

**Comment by Superhepper** [comment]
Hi. I am sorry to hear that you ran into some problem. I am a little confused about the function you posted. Is that a function you written your self? Because the functions in the tests do not take any arguments.

My guess here is that the ```vec``` passed into this function does not require the amount of bytes expected for 2048bit RSA key. As you can see,, in the tests, for a 2048 RSA key the private data *must* consist of 128 bytes any other sizes will probably result in an error.

**Comment by DNJha** [comment]
Hi @Superhepper, 

Yes, I wrote the function by updating the example as the example uses [PRIV_KEY](https://github.com/parallaxsecond/rust-tss-esapi/blob/ac7efa40cbcbb50eadd9b30e5360273f91a7900d/tss-esapi/tests/integration_tests/context_tests/tpm_commands/object_commands_tests.rs#L169) on [Line 183](https://github.com/parallaxsecond/rust-tss-esapi/blob/ac7efa40cbcbb50eadd9b30e5360273f91a7900d/tss-esapi/tests/integration_tests/context_tests/tpm_commands/object_commands_tests.rs#L183), which I'm passing as an argument (Vec\<u8\>) without changing anything else.

> Takes data that is 128 bytes and converts it into 2048bit RSA key.

Sorry, I'm a little confused. Based on my understanding, we can pass a public-private key pair (KEY and PRIV_KEY in the example) generated previously to be loaded to the TPM using `load_external`. To convert the keys to the TPM-loadable format, we are using `get_ext_rsa_priv` and `get_ext_rsa_pub`. Please correct me if I misunderstood.

This is what I want to do i.e., load a previously generated key-pair to TPM using `load_external`.

**Comment by Superhepper** [comment]
Yes, the load_external function loads an external key into the TPM. But I would like to know what kind of data you are trying to load. Because it is not possible to generate a key-pair in PEM format and then just read the data of the file directly and try to load it into the TPM.

**Comment by DNJha** [comment]
I've created a key-pair in pem format. Next, I converted the pem format public and private key to the Vec\<u8\>. Later I tried to use the `get_ext_rsa_priv` and `get_ext_rsa_pub` to convert it to the TPM-loadable format so that I can use the load_external function. With the example data everything is working fine but with my key, I got stuck at the `get_ext_rsa_priv` with the given error.

I'm not sure if I'm doing anything wrong.

**Comment by Superhepper** [comment]
I think you need to extract the exponent data from the pem file.

"11.2.4.7 TPM2B_PRIVATE_KEY_RSA
This sized buffer holds the largest RSA prime number supported by the TPM.
NOTE 1 All primes are required to have exactly half the number of significant bits as the public modulus, and the square of each prime is required to have the same number of significant bits as the public modulus.
NOTE 2 RSA_PRIVATE_SIZE is a vendor specific value that can be (MAX_RSA_KEY_BYTES / 2) or ((MAX_RSA_KEY_BYTES * 5) ./ 2. The larger size would only apply to keys that have fixedTPM parents. The larger size was added in revision 01.53."

**Comment by DNJha** [comment]
Can you please suggest any example if possible, thank you

**Comment by Superhepper** [comment]
I think you would have to use something that can parse your PEM file. Like the OpenSSL crate.

So lets say you have a key pair on disk in pem format and you use the openssl crate. Then you would have to do something like this:
```rust
let file_path = std::fs::Path("rsa.priv");
let rsa_private_file_pem = std::fs::read(file_path).expect("Failed to read file");

let rsa_key = openssl::rsa::Rsa::private_key_from_pem(&rsa_private_file_pem).expect("Failed to read RSA key from file");

let private_exponent_data = rsa_key.d().expect("No private exponent in the key").to_vec();

tss-esapi::structures::Sensitive::Rsa {
            sensitive: private_exponent_data .try_into().expect("Failed convert private_exponent_data to Sensitive"),
            auth_value: Default::default(),
            seed_value: Default::default(),
}
```
