### ISSUE TITLE
Compilation support for tpm2-tss 4.0

### ISSUE THREAD

**Issue by aplanas** [parallaxsecond/rust-tss-esapi#382]
Recently 4.0.0-rc1 has been published, and the current build.rs consider this version as a non-valid.

**Comment by Superhepper** [comment]
Yes, we have not done any testing with the new version. So it is not supported because most likely there are some API breaking changes that we need to look into.

**Comment by ionut-arm** [comment]
Indeed, I'd wait until the actual release is out before doing any compatibility testing. I'm also somewhat worried that even if the interface "looks" the same, there might be some breaking changes in terms of the contract for the operations - thankfully we have quite comprehensive testing, but I'm still paranoid.

**Comment by aplanas** [comment]
4.0.0 has been released: https://github.com/tpm2-software/tpm2-tss/releases/tag/4.0.0

**Comment by ansasaki** [comment]
Could you please prioritize this, if possible? 

Currently, it is not possible to build `rust-tss-esapi` on Fedora Rawhide because the only available version of `tpm2-tss` is `4.0.1` ( https://github.com/tpm2-software/tpm2-tss/releases/tag/4.0.1). We cannot build anything that depends on `rust-tss-esapi` as well, like `rust-keylime`.

**Comment by ionut-arm** [comment]
Yes, sure, thanks for making us aware.

What version of `tss-esapi` (or `tss-esapi-sys`) are you interested in? An update to v7?

I've done a small test locally that seemed to confirm that the vast majority of things work fine with tpm2-tss v4.0.0.

**Comment by nullr0ute** [comment]
Yes please, we currently have rust-tss-esapi 7.1.0 in Fedora and tpm2-tss 4.0.1 and tpm2-tools 5.5-rc1 in rawhide (F-38+)

**Comment by aplanas** [comment]
We blocked tpm2-tss upgrade in openSUSE waiting for this. @ionut-arm is there something that I can do to help? #386 update the bindgen, maybe I can try to generate new bindings and see what is broken?

**Comment by ionut-arm** [comment]
Hi both, I'm working on fixing and porting #388 into the v7 branch, I'll do a release ASAP after that's done.

**Comment by ionut-arm** [comment]
Hi all, v7.2.0 of `tss-esapi` has now been released with support for tpm2-tss 4.0. Please let me know if there's any problem on your side, and if not we'll close this.

**Comment by aplanas** [comment]
Thanks a lot! I will proceed to release tpm2-tss 4.X in openSUSE

**Comment by nullr0ute** [comment]
Update in Fedora in progress as well. Thanks.
