### ISSUE TITLE
Create Rust-native TPM2_ALG_ID wrapper

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#40]
There's a lot of usage of the TPM2_ALG_ID type which is essentially a glorified int. Having a Rust enum would allow *much* better enforcement of allowed values.

Methods for discovering various traits about the algorithms, as defined in Part 2, Section 6.3 of the specification, should also be implemented.

**Comment by Superhepper** [comment]
I think I will need to adress this before I can continue on rustification of pcr_read.
