### ISSUE TITLE
No 7.3.0 tag in git

### ISSUE THREAD

**Issue by nullr0ute** [parallaxsecond/rust-tss-esapi#435]
There's a 7.3.0 release in crates.io (https://crates.io/crates/tss-esapi/7.3.0) but no corresponding git tag (as of 21/9/23 08:30 BST) to match. Please ensure the release process also covers pushing tags that match the release.

**Comment by ionut-arm** [comment]
Done, thanks for the notice! :)

**Comment by wiktor-k** [comment]
One way to avoid this kind of problems would be to add a CI job that'd publish the crate on crates.io using [scoped tokens](https://blog.rust-lang.org/2023/06/23/improved-api-tokens-for-crates-io.html) when a new tag is pushed to the repo. The job itself is [pretty simple](https://github.com/wiktor-k/unimpl/blob/main/.github/workflows/publish.yml).

Of course whether this is acceptable to publish creates from CI pipelines is another question but having scoped tokens is definitely one factor that makes them safer to deploy.

:wave:
