### ISSUE TITLE
Implement secure data management

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#46]
Currently all data passed to/through the library is released as-is once it is dropped. We should ideally clean up all the objects we use and all input we get from clients.

See https://github.com/parallaxsecond/parsec/issues/122 for more details.

**Comment by paulhowardarm** [comment]
What work is required here over and above https://github.com/parallaxsecond/parsec/issues/122 ?

**Comment by ionut-arm** [comment]
> 
> 
> What work is required here over and above [parallaxsecond/parsec#122](https://github.com/parallaxsecond/parsec/issues/122) ?

[parallaxsecond/parsec#122](https://github.com/parallaxsecond/parsec/issues/122) only covers the Parsec service side of things. This covers the whole of the TSS crate, but for the Parsec issue we can go and make the changes specific to us.
