### ISSUE TITLE
Allow Context to be unwrapped to ESYS_CONTEXT

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#50]
Usage of the `Context` structure is fairly limited by the number of methods implemented on it. This restriction could be lifted if the `Context` could be unwrapped to expose the `ESYS_CONTEXT` beneath. 

This should be a one-way call, as once this is done, we can no longer keep track of generated handles. 

My suggestion would be to bundle up the Esys and TCTI contexts together with the handle set in a "shell" structure that is only used to access them. This would be incorporated in the `Context` to let it work as usual. Additionally, closing the contexts could be delegated to a custom implementation of `Drop` for the new structure.

**Comment by hug-dev** [comment]
Seems like a good temporary solution for those wanting to use ESYS methods that we do not implement!
Some questions:
* will those method only need reference to `ESYS_CONTEXT`? So that the `drop` method does not get called prematurely
* should that method be unsafe?

**Comment by hug-dev** [comment]
Is it still needed now that we have increased our support?

**Comment by Superhepper** [comment]
Personally I do not think it is necessary. It is better handled with getting bugs or requests for missing API:s.

**Comment by hug-dev** [comment]
> It is better handled with getting bugs or requests for missing API:s.

Agree with that!
