### ISSUE TITLE
Dependency mbox 0.6.1 which hard requires Rust 2018

### ISSUE THREAD

**Issue by jzaehrin** [parallaxsecond/rust-tss-esapi#519]
The release of mbox 0.6.1 now strongly requires Rust 2018 to compile by forcing [severely out-dated dependency versions](https://github.com/kennytm/mbox/blob/v0.6.1/Cargo.toml#L30-L36). Version 0.6.0 was yanked from crates.io which blocks the compilation of tss-esapi with a more recent version of Rust and a missing `Cargo.lock`.

tss-esapi 8.0.0 should replace mbox which is a good thing.

In the meantime, could it be possible to update mbox to 0.7.1 or force 0.6.0?

The difference between 0.6.1 and 0.7.1 is very small, not impacting the code only on the dependencies and compilation context: [mbox v0.6.1 commits](https://github.com/kennytm/mbox/commits/v0.6.1/).

**Comment by petreeftime** [comment]
https://github.com/parallaxsecond/rust-tss-esapi/pull/520 Created a PR for this issue.

**Comment by ionut-arm** [comment]
I believe this is solved, please re-open / comment if that's not the case
