### ISSUE TITLE
Add Quote support

### ISSUE THREAD

**Issue by genofire** [parallaxsecond/rust-tss-esapi#52]

**Comment by ionut-arm** [comment]
I'll look into doing that - any use cases/methods in particular that you'd like to see supported?

**Comment by genofire** [comment]
Me too ;) - but that are my first steps, so a would really need long time to figure out how (it does not work on a hackyway yet).

for **PCR**, i think arguments like `(HASH_AGL, vec![pcr_nr,pcr_nr]) -> vec![hash,hash,..]` whould be enougth.

More complex is a **quote**, i do not know yet ... (in my project i have three weeks to solve it :smile: )

**Comment by ionut-arm** [comment]
Will have a look later today and try and figure out how `quote` works and what could be added!

So for PCRs you don't need to measure anything in them, just reading a previous measurements? That shouldn't be too hard, I guess

**Comment by Superhepper** [comment]
I realised that I am in need of the pcr read functionality as well. If you want me to I can start working on that.

**Comment by genofire** [comment]
@Superhepper youhave that job :+1:  - you could announce me as reviewer :smile:

**Comment by ionut-arm** [comment]
Thanks, guys! Again, I'll look at `quotes` later and I'll review incoming PRs asap

**Comment by ionut-arm** [comment]
Cool, got some code almost ready, it just needs some Rusting up - will probably have a PR tomorrow (probably for both `Read_PCR` and `Quote`)

**Comment by Superhepper** [comment]
Oh .. And I finished the pcr_read I was working on yesterday. And it seamed to work. Though it was just a thin wrapper nothing fancy. Because that API would really need a utility struct that allows you to build up the parameter structure. Because every time I try to write those selection structures I usually get lost in what layer I am.

**Comment by ionut-arm** [comment]
@Superhepper - would you be ok with me merging your PCR read PR and raising a PR myself for Quote (and potentially other PCR-related methods, to make testing more comprehensive)? You can carry on doing the type updates in a different PR, but since you both need PCR read it makes sense to just merge it as it is.

**Comment by Superhepper** [comment]
Go ahead.

**Comment by ionut-arm** [comment]
Thanks for contributing that!

**Comment by genofire** [comment]
Now we need only to get a Quote :+1: thank you for the PCR_Read ;)

**Comment by Superhepper** [comment]
We should close this. Because it has been solved with #67.

**Comment by ionut-arm** [comment]
@genofire have you had time to test the quote support? 

We can close once that's confirmed!

**Comment by genofire** [comment]
I will test it next week :)

**Comment by genofire** [comment]
Works for me ;)
It is still a little bit strange to use ....
e.g.
- howto convert TPM2B_ATTEST.attestationData to TPMS_ATTEST a  (found something uptream which looks a little bit in this direction: https://github.com/tpm2-software/tpm2-tools/pull/1815)
- howto verify the signature

**Comment by genofire** [comment]
```
impl TryInto<TPMS_ATTEST> for TPM2B_ATTEST {
    type Error = std::io::Error;
    fn try_into(self) ->  Result<TPMS_ATTEST, Self::Error> {
        let mut c = Cursor::new(self.attestationData.as_slice());
        let mut ret = TPMS_ATTEST::default();

        ret.magic = c.read_u32::<NetworkEndian>()?;
        ret.type_ = c.read_u16::<NetworkEndian>()?;

        // qualifiedSigner
        ret.qualifiedSigner.size = c.read_u16::<NetworkEndian>()?;
        let mut d = vec![0; ret.qualifiedSigner.size as usize];
        c.read(&mut d)?;
        for (i, e) in d.iter().enumerate() {
            ret.qualifiedSigner.name[i] = (*e).into();
        }

        // extraData
        ret.extraData.size = c.read_u16::<NetworkEndian>()?;
        let mut d = vec![0; ret.extraData.size as usize];
        c.read(&mut d)?;
        for (i, e) in d.iter().enumerate() {
            ret.extraData.buffer[i] = (*e).into();
        }

        ret.clockInfo.clock = c.read_u64::<NetworkEndian>()?;
        ret.clockInfo.resetCount = c.read_u32::<NetworkEndian>()?;
        ret.clockInfo.restartCount = c.read_u32::<NetworkEndian>()?;
        ret.clockInfo.safe = c.read_u8()?;

        ret.firmwareVersion = c.read_u64::<NetworkEndian>()?;

        let mut quote = tss_esapi::tss2_esys::TPMS_QUOTE_INFO::default();
        quote.pcrSelect.count = c.read_u32::<NetworkEndian>()?;
        for i in 0..quote.pcrSelect.count as usize {
            quote.pcrSelect.pcrSelections[i].hash = c.read_u16::<NetworkEndian>()?;
            quote.pcrSelect.pcrSelections[i].sizeofSelect = c.read_u8()?;
            for j in 0..quote.pcrSelect.pcrSelections[i].sizeofSelect as usize {
                quote.pcrSelect.pcrSelections[i].pcrSelect[j] = c.read_u8()?;
            }
        }
        quote.pcrDigest.size = c.read_u16::<NetworkEndian>()?;
        let mut d = vec![0; quote.pcrDigest.size as usize];
        c.read(&mut d)?;
        for (i, e) in d.iter().enumerate() {
            quote.pcrDigest.buffer[i] = (*e).into();
        }

        ret.attested = tss_esapi::tss2_esys::TPMU_ATTEST { quote: quote};

        Ok(ret)
    }
}
```
