### ISSUE TITLE
Bring Context method names closer to the TSS API

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#58]
The method names on `Context` should be as close to the TSS function names to make it easy for developers to reference them from the specs or previous experience with the TPM stack.

**Comment by ionut-arm** [comment]
This can be expanded to cover struct names in the utils folder.

**Comment by hug-dev** [comment]
Is that part of #87?

**Comment by Superhepper** [comment]
Yes, part of that have been fixed in #87 but not all of it I think.

**Comment by ionut-arm** [comment]
This seems like a duplicate of #87 in disguise. Will close this one, we can agree on a proper structure under 87 and then have separate issues to implement the change (probably for 6.x.y)
