### ISSUE TITLE
Add policy pcr support.

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#64]
Currently it is not possible to create any policies(I think). The pull #63 adds some nice improvement to the creation of pcr selections that will be very useful for making it possible to create a policy from pcr values. I suggest that this issue will include the following.

1. Improve the return value of the `pcr_read` api.
2. Create a new api for creating a policy from pcr values (policy_pcr) that can use the improved return value from read_pcr as input.

**Comment by hug-dev** [comment]
Can this now be closed or more work is needed on this topic?

**Comment by Superhepper** [comment]
This can be closed now.
