### ISSUE TITLE
Create a session object.

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#66]
Currently when sessions are used it has been enough to only provide the session handle (i.e. ESYS_TR). For some of the api:s that needs to be developed this information is not enough. So the session handle needs to be wrapped inside of our own session struct and be deployed. So that it will be easier to add more information regarding the session in the future.

**Comment by hug-dev** [comment]
Is that dealt with #108 ?

**Comment by Superhepper** [comment]
No, the session object needs more information I think. The handle is just one piece of information needed. It could also prove useful to know with what hashing algorithm the session was created.

**Comment by Superhepper** [comment]
#120 have now been merged. This adds session objects.
