### ISSUE TITLE
Split between tss-esapi and tss-esapi-sys

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-tss-esapi#75]
We should split this repository between two crates:
* `tss-esapi-sys` which role is to find and/or compile the ESAPI libraries, provide the unsafe bindgen types and functions
* `tss-esapi` which contains higher-level safe Rust constructs

The principle is explained [here](https://kornel.ski/rust-sys-crate).

**Comment by ionut-arm** [comment]
It's worth considering how the types that will be exposed from the `*-sys` crate are chosen. I assume people might be interested in using types that we're not aware of, so attempting to only publish the types that we`re interested in might backfire. 

We could expose all of them as a module and re-publicise the "important" ones straight from the root of the crate.
