### ISSUE TITLE
the trait `std::error::Error` is not implemented for `tss_esapi::response_code::Error

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#77]
An implementation for the std::error::Error should be available for our Error type. Not having that makes it complicated to wrap or box our errors.

**Comment by ionut-arm** [comment]
Unless you're already planning to implement this asap, I can implement this today.

**Comment by Superhepper** [comment]
No, I had no plans to implement this right now. So it would be wonderful if you could do it.

**Comment by hug-dev** [comment]
> Not having that makes it complicated to wrap or box our errors.

I was curious about the benefit of implementing `Error`, do you have an exemple for this?

**Comment by Superhepper** [comment]
If do not implement this then the users would have to write their own mappings for our errors or simply ignore what the error we sent was.



If you would like to do the following
```rust
let (_uc, pcr_sels, pcr_data) = ctx.pcr_read(pcr_selections)?;
```
in your code using our library and you have your own error type. And then want
to preserve the underlying error. Then you want to perform a conversion from the tss_esapi error into your own. Which becomes complicated if the the tss_esapi error does not implement the std::error::Error trait.

I think most guides regarding error handling in rust assumes that the std::error::Error trait is implemented for the error they show how to wrap or box.

**Comment by hug-dev** [comment]
Sounds useful!
