### ISSUE TITLE
Handle breaking changes in tpm2-tss from 2.4.0

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#80]
I am just putting this here to remind us. That tpm2-tss 2.4.0 and greater introduces some breaking changes. Because this is in alpha we have the possibility to just increase the required version of tpm2-tss. But I am not sure which path is the best.

**Comment by Superhepper** [comment]
I will have look and see if I can improve things.

**Comment by Superhepper** [comment]
Unfortunately there is not much to improve. The different types in this case are just type aliases for u32. So I could not think of any trick / hack in order to figure out what values to use.

1. We move everything to the latest tpm2-tss 2.4.X. Fix all tests and things that breaks with this change. And be done with it.

2. We try to maintain backwards compatibility by looking at the version in pkgconfig and do necessary adjustments in the code with regard to version.

Personally I would vote for number 1. But what do you guys think @hug-dev @ionut-arm ?

**Comment by hug-dev** [comment]
I think since we are still on alpha releases, it is fine and expected to do breaking changes. So I would say that we can improve the `tpm2-tss` version we support. Is the hierarchy type the only breaking change?

**Comment by Superhepper** [comment]
I have begun doing some testing with running the CI container with updated versions. And it seams to be more things that breaks. I will look into it further and see why those things stops working.

**Comment by Superhepper** [comment]
It seams as the breaking change in 2.4.X was removed, And they moved it into 3.0.0-dev version of the library. But I am going to continue to look at upgrading I am still finding some issues with it that I need to resolve.

The following tests are still failing and I need to understand why:
    two_signatures_different_digest
    verify_wrong_digest
    verify_wrong_key

**Comment by ionut-arm** [comment]
I'll try it out as well when I get a bit of free time!

Are those failing with a reasonable error or is it something obscure/non-intuitive?

**Comment by Superhepper** [comment]
Well now it is only failing on my machine. In #84 I uploaded a draft PR to see if the CI would be able to run it and that worked fine.

**Comment by hug-dev** [comment]
Can we close this issue?

**Comment by Superhepper** [comment]
Yes. I am not sure if we have made another issue for the things we discussed with regard to having two different builds in CI. One with MIN_VERSION = 2.3.3 and one with latest compatible 2.x.x?

**Comment by hug-dev** [comment]
Ok I will rename that issue to be just that.

**Comment by hug-dev** [comment]
Actually created a new one.
