### ISSUE TITLE
Adding Superhepper as a contributor

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-tss-esapi#82]
Hi @Superhepper ,

If @ionut-arm can confirm, I would like to propose to add you as a contributor and give you Triage right. As you contribute frequently to this crate, it will be a bit easier for you to manage issues and pull requests.

@Superhepper Would you be happy to become a contributor?

**Comment by ionut-arm** [comment]
I'm more than happy with the proposal!

**Comment by Superhepper** [comment]
Absolutely! It would be an honour.  Hehe.

**Comment by hug-dev** [comment]
Awesome, you should have received an invitation, thank you 🥳

**Comment by hug-dev** [comment]
Please feel free to assign yourself to pull-request or issues and ask people for reviews!
