### ISSUE TITLE
Commit the ESAPI bindings if the ABI is stable

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-tss-esapi#85]
We should check if the ESAPI ABI is stable and if it is, commit inside the repository (or in `tss-esapi-sys`) the bindgen bindings that we currently generate everytime during compilation.

That has multiple advantages:
* make the compilation faster, without the bindgen step
* simplify the build script
* we would be able to use for docs.rs

**Comment by ionut-arm** [comment]
Going 180 on this, eh. I think the interface is stable, it's only library changes that might occur so this would make sense (but I do prefer creating a `sys` crate instead of just committing bindgened code).

**Comment by hug-dev** [comment]
> but I do prefer creating a sys crate instead of just committing bindgened code

That would be part of the `sys` crate still! With only that file in it basically and means to do linking. I had this idea over re-reading [this](https://kornel.ski/rust-sys-crate#abi).

**Comment by Superhepper** [comment]
So we should use the latest version of tpm2-tss and only generate new bindings when a new version is released? Hrmm how much faster build times are we talking about?

**Comment by hug-dev** [comment]
Well I was hoping that since the TCG TSS 2.0 ESAPI is specified and stable (version 1.0), once the `tpm2-tss` implementation is compliant there would not be breaking changes with different versions of the implementation, unless the specification itself does a breaking change.
We would say that this crate is a wrapper around version 1.0. and work with all compliant implementations. But maybe it is more complicated than that!
