### ISSUE TITLE
Log the commands sent and received to/from the TPM

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-tss-esapi#86]
As per [mitigation 4 of our Parsec Threat Model](https://parallaxsecond.github.io/parsec-book/threat_model/threat_model.html#mitigations), commands sent and received to/from the TPM should be logged.

We can close this issue (and keep it for record) if the logging is already done by the TSS libraries (I think it is).

**Comment by Superhepper** [comment]
I think that logging is already done by the TSS library [tpm2-tss logging](https://github.com/tpm2-software/tpm2-tss/blob/master/doc/logging.md). But there might be other things that we are interested in?

**Comment by hug-dev** [comment]
Great, I did not know! With `TSS2_LOG=all+TRACE` a lot of logs are print including all values (un)marshalled.
I think though that the amount of logging is so big that most deployments won't activate them and hence lose the anti-repudiation information. Maybe it would be best to add logging in this crate for every ESYS operation?

**Comment by ionut-arm** [comment]
> Maybe it would be best to add logging in this crate for every ESYS operation?

Is there no option in-between logging _EVERYTHING_ and nothing? :( 

I'm guessing there's enough confidence in leaving the TSS lib to log stuff if that's possible - it could be that the TSS logs something from another process and it would be more difficult to follow, but at the same time someone else could be using this crate.

**Comment by hug-dev** [comment]
Unfortunately the only information seems to be that data exchanged, at the trace/debug level.

**Comment by ionut-arm** [comment]
> 
> 
> Unfortunately the only information seems to be that data exchanged, at the trace/debug level.

Based on the [page](https://github.com/tpm2-software/tpm2-tss/blob/master/doc/logging.md) linked above, it seems you can just do `TSS2_LOG=all+ERROR` and just get some information logged in case of an error - would that not be relevant?

**Comment by hug-dev** [comment]
I think ideally, for the repudiation threat, all operations would need to be logged and not only errors :/

**Comment by ionut-arm** [comment]
Logging is probably the weakest attempt at non-repudiation there can be: https://security.stackexchange.com/questions/1786/how-to-achieve-non-repudiation

I really don't think we can sanely tell anyone "hey, enable logs to have proof that the operations were performed by X" without being laughed at.. Especially telling them "enable trace logs in production", that'll drown them in useless information (or useful to the attacker, depending just how much info you print). Might be better to just stick to "we assume no repudiation will happen with trusted clients 😇 "

**Comment by ionut-arm** [comment]
As in, just logging that user X did operation Y is not enough against repudiation claim - you have to show what arguments were passed as well, so that's essentially the `TRACE` log above

**Comment by hug-dev** [comment]
I agree with you on that logging for anti-repudiation is not ideal. This requirement is coming from the Parsec Threat Model as a mitigation for a repudiation threat. If we find another way to mitigate the possible threat, or add an assumption/non-mitigation this this kind of threat is not covered, I would be happy to close this issue

**Comment by ionut-arm** [comment]
It is, but we wrote that and didn't have much feedback, not on that at least - my idea was to change that to an unmitigation, it's not like we don't do that for other "threats". I'm just afraid of how this might be perceived, as foolish or missing the point. Plus, if we don't log all the data that goes into the operations then the "mitigation" simply doesn't work, it doesn't do what we want - you can't prove that some client sent a particular request and got a particular response...

**Comment by hug-dev** [comment]
Ok let's put the corresponding "threats" as unmitigated
